# Generated by Django 3.1.7 on 2021-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('question', 'question'), ('image', 'image')], default='question', max_length=10),
        ),
    ]
