# Generated by Django 3.1.7 on 2021-03-11 14:09

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('code', models.CharField(default='xmod', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='def_user.jpg', upload_to=account.models.user_directory_path, verbose_name='Avatar')),
                ('bio', models.TextField(default='User has no biography yet', verbose_name='Biograpthy')),
                ('first_join', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('user', 'user'), ('junior', 'junior'), ('moderator', 'moderator')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('first_join',),
            },
        ),
    ]
