# Generated by Django 3.1.7 on 2021-03-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
